#!/usr/bin/env bash
#
# Script name: dm-currencies
# Description: Convert prices between currencies using https://rate.sx
# Dependencies: dmenu and curl
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: ifrendas

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {

  from_unedited="$(printf "%s\n" "$currency_list" | ${DMENU} "Convert from:")"
  to_unedited="$(printf "%s\n" "$currency_list" | ${DMENU} "Convert to:")"
  amount="$(echo "" | ${DMENU} "How much (number only):")"

  from="$(echo $from_unedited | cut -d: -f1)"
  to="$(echo $to_unedited     | cut -d: -f1)"

  converted="$(curl "https://currencyconvert.online/$from/$to/$amount" | grep "How much is <b>" | sed "s/Look at.*//g" | sed "s/.*— //g")"

  notify-send "Converted amount (in clipboard)" "$converted"
  echo "$converted" | cp2cb
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
