#!/usr/bin/env bash
#
# Script name: dm-sounds
# Description: Choose a ambient background sound to play
# Dependencies: dmenu, ffmpeg
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Francesco Prem Solidoro
#
# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.

# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null
init_dmscript "$@"


main(){
  # wm=$(printf "%s" wm_list[@] | ${DMENU} "pick a WM")
  theme=$(find "$HOME"/.local/src/suckless/dwm/colors/* | cut -d / -f9- | sed -e s/colors.h//g | sort | ${DMENU} "Pick a Theme")
  cd "$HOME"/.local/src/suckless/dwm/colors || exit
  rm colors.h
  cp "$theme" colors.h
  cd ..
  $SUDO_ASKPASS make install
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
