#!/usr/bin/env bash
#
# Script name: dm-reddit
# Description: Dmenu as a reddit viewer using reddio.
# Dependencies: dmenu, reddio, yad
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               HostGrady
#               Simon Ingelsson

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null
init_dmscript "$@"

main() {
  # Picking a subreddit from the above reddit_list.
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154
  reddit_list+=( "Quit" )
  _subreddit=$(printf '%s\n' "${reddit_list[@]}" | ${MENU} "Choose a subreddit:" "$@") || exit 1

  # Show the last 20 posts (titles and ids) from the chosen subreddit.
  post_title=$(bash reddio print -f '$num. $title $id$nl' -l 20 "$_subreddit" | \
  ${MENU} 'Last 20 posts on '"$_subreddit" "$@")

  # Display contents of chosen post in a yad text box.
  post_id=$(printf '%s\n' "${post_title##* }")
  bash reddio print -f ' TITLE: $title$nl SUBMITTED: $created_pretty$nl AUTHOR: $author$nl$nl$text' by_id/"$post_id" | \
  yad --text-info --height=600 --width=600 || exit 1
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"

