#!/bin/bash
#
# Script name: dm-dictionary
# Description: uses the translate package as a dictionary
# Dependencies: translate-shell, didyoumean
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Francesco Prem Solidoro

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.

# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null
init_dmscript "$@"

main(){
  specials=("ə" "¯\\_(ツ)_/¯" "(╯°□°）╯︵ ┻━┻" "┬─┬ ノ( ゜-゜ノ)" "∈]-∞; 3[" "( ͡° ͜ʖ ͡°)" "(づ๑•ᴗ•๑)づ♡" "( ´･ω･)人(・ω・｀ )" "ʚ♡⃛ɞ(•ᴗ•❁)")
  if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  printf "%s\n", "${specials[@]}"  | ${DMENU} "Special Characters: ", "$@" | sed -e "s/,//" | wl-copy
else
  printf "%s\n", "${specials[@]}"  | ${DMENU} "Special Characters: ", "$@" | sed -e "s/,//" | xclip -selection clipboard
  fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
