#!/usr/bin/env bash
#
# Script name: dm-dictionary
# Description: Uses didyoumean as a spellchecker.
# Dependencies: dmenu, fzf, rofi, didyoumean
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Francesco Prem Solidoro
#               Derek Taylor

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null
init_dmscript "$@"

main() {
    WORD="$(printf '%s' "" | ${MENU} "Enter Word:")"

    if ! [ "${WORD}" ] || [ "${WORD}" = "quit" ]; then
        printf 'No word inserted\n' >&2
        exit 0
    fi

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
dym -c "$WORD" | ${DMENU} "Select Correct Spelling:" | wl-copy
else
dym -c "$WORD" | ${DMENU} "Select Correct Spelling:" | xclip -selection clipboard
fi
}

MENU="$(get_menu_program "$@")"
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
